"""Block catalog generator for MCC automation.

Two modes:

  MODE A — Read from CSV generated by the AutoLISP scanner (recommended):
    1. In AutoCAD command line:
         (load "C:/path/to/lisp/scan_blocks.lsp")
         (mcc-scan-folder "C:/path/to/8PX3 Blocks" "C:/temp/mcc_attdefs.csv")
    2. Then run:
         python scripts/generate_catalog.py --from-csv "C:/temp/mcc_attdefs.csv" --dir "C:/path/to/8PX3 Blocks"

  MODE B — Direct COM scan (requires working SendCommand, may fail on AutoCAD 2027):
    python scripts/generate_catalog.py --dir "C:/path/to/8PX3 Blocks"

Options
-------
  --from-csv  PATH   CSV produced by scan_blocks.lsp  (Mode A)
  --dir       PATH   Directory of .dwg files  (required in both modes)
  --out       PATH   Output YAML (default: mcc_block_catalog.yaml in repo root)
  --merge            Merge into existing catalog instead of overwriting
  --verbose          Print attribute tags for each block
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any


def _check_deps():
    try:
        import yaml
    except ImportError:
        print("pyyaml not installed. Run: pip install pyyaml")
        sys.exit(1)

_check_deps()
import yaml


# ---------------------------------------------------------------------------
# CSV parser (output from scan_blocks.lsp)
# ---------------------------------------------------------------------------
def load_csv(csv_path: Path) -> dict[str, list[str]]:
    """Parse the CSV produced by scan_blocks.lsp.

    Returns dict:  filename_stem -> [TAG1, TAG2, ...]
    INST: prefix means it was an AcDbAttribute instance rather than an ATTDEF.
    """
    import csv
    results: dict[str, list[str]] = {}
    with open(csv_path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            name = Path(row.get("filename", "")).stem
            raw_tags = row.get("tags", "")
            if raw_tags in ("ERROR_OPEN", ""):
                tags = []
            else:
                tags = [t.strip() for t in raw_tags.split("|") if t.strip()]
            results[name] = tags
    return results


# ---------------------------------------------------------------------------
# Section heuristics + attribute map guesser
# ---------------------------------------------------------------------------
_SECTION_PATTERNS = [
    re.compile(r"(?i)(mcc[_\-\s]?sect)"),
    re.compile(r"(?i)(sect[_\-\s]?\d{3,4}w?)"),
    re.compile(r"(?i)(\d{3,4}[_\-\s]?w[_\-\s]?sect)"),
    re.compile(r"(?i)(8px3[_\-\s]?\d{3,4})"),
    re.compile(r"(?i)(section[_\-\s]?\d{3,4})"),
]
_WIDTH_EXTRACT = re.compile(r"(\d{3,4})")

def _looks_like_section(name: str) -> bool:
    return any(p.search(name) for p in _SECTION_PATTERNS)

def _extract_width(name: str) -> int | None:
    m = _WIDTH_EXTRACT.search(name)
    if m:
        val = int(m.group(1))
        if 300 <= val <= 1200:
            return val
    return None

_ATTR_GUESSES: list[tuple[re.Pattern, str]] = [
    (re.compile(r"(?i)^(sect|section|unit.?no|unit.?num)$"),   "section_id"),
    (re.compile(r"(?i)^(desc|description|load.?desc)"),         "description"),
    (re.compile(r"(?i)^(hp|horse.?power|kw)$"),                "hp"),
    (re.compile(r"(?i)^(volt|voltage|kv)$"),                   "voltage"),
    (re.compile(r"(?i)^(fla|full.?load|current)$"),            "fla"),
    (re.compile(r"(?i)^(type|starter.?type|unit.?type)$"),     "starter_type"),
    (re.compile(r"(?i)^(cat|catalog|cat.?no|part.?no)$"),      "catalog_no"),
    (re.compile(r"(?i)^(ord|order|job.?no)$"),                 "order_no"),
    (re.compile(r"(?i)^(frame|breaker.?frame)$"),               "breaker_frame"),
    (re.compile(r"(?i)^(trip|trip.?a)$"),                      "breaker_trip"),
    (re.compile(r"(?i)^(fuse|fuse.?a|fuse.?amp)$"),            "fuse_amp"),
    (re.compile(r"(?i)^(coil|coil.?v|coil.?volt)$"),           "coil_voltage"),
    (re.compile(r"(?i)^(overload|ol.?range|range)$"),          "ol_range"),
    (re.compile(r"(?i)^(ctrl.?va|ctl.?va|xfmr.?va)$"),        "ctrl_xfmr_va"),
]

def _guess_attr_map(tags: list[str]) -> dict[str, str]:
    result: dict[str, str] = {}
    used: set[str] = set()
    for tag in tags:
        clean = tag.removeprefix("INST:")
        for pattern, key in _ATTR_GUESSES:
            if key not in used and pattern.match(clean):
                result[key] = clean
                used.add(key)
                break
    return result


# ---------------------------------------------------------------------------
# Catalog builder
# ---------------------------------------------------------------------------
def build_catalog(
    block_dir: Path,
    scan_data: dict[str, list[str]],
    verbose: bool,
) -> dict[str, Any]:

    dwg_files = sorted(block_dir.glob("*.dwg"), key=lambda p: p.name.lower())
    dwg_files += [f for f in sorted(block_dir.glob("*.DWG"), key=lambda p: p.name.lower())
                  if str(f).lower() not in {str(x).lower() for x in dwg_files}]

    print(f"Found {len(dwg_files)} .dwg files in {block_dir}")
    print(f"Attribute data available for {len(scan_data)} files\n")

    blocks: dict[str, Any] = {}
    mcc_sections: dict[Any, Any] = {}
    n_with_attrs = 0

    for dwg in dwg_files:
        name = dwg.stem
        tags = scan_data.get(name, scan_data.get(name.upper(), scan_data.get(name.lower(), [])))
        # Strip INST: prefix for display; keep track of which were instances
        clean_tags = [t.removeprefix("INST:") for t in tags]
        has_instances = any(t.startswith("INST:") for t in tags)

        if tags:
            n_with_attrs += 1

        note = " (attribute instances — block saved with insertion)" if has_instances and not any(not t.startswith("INST:") for t in tags) else ""
        print(f"  {name:40s} {len(clean_tags):3d} tags{note}")

        if verbose and clean_tags:
            print(f"    {clean_tags}")

        blocks[name] = {
            "description": f"Block: {name}",
            "file_path": dwg.name,
            "attributes": clean_tags,
        }

        if _looks_like_section(name):
            width = _extract_width(name)
            attr_map = _guess_attr_map(tags)
            entry = {
                "block_name": name,
                "description": f"{width}mm MCC section" if width else name,
                "file_path": dwg.name,
                "attribute_map": attr_map or {
                    "section_id": "SECT", "description": "DESC",
                    "hp": "HP", "voltage": "VOLT", "fla": "FLA",
                    "starter_type": "TYPE", "catalog_no": "CAT", "order_no": "ORD",
                },
                "_detected_attributes": clean_tags,
            }
            key = width if width else name
            if key not in mcc_sections:
                mcc_sections[key] = entry

    print(f"\n{n_with_attrs}/{len(dwg_files)} files had attribute data")

    return {
        "library_paths": [str(block_dir)],
        "layout": {"start_x": 0, "start_y": 0, "direction": "horizontal"},
        "mcc_sections": dict(sorted(mcc_sections.items(), key=lambda x: (isinstance(x[0], str), x[0]))),
        "blocks": blocks,
    }


# ---------------------------------------------------------------------------
# Merge + write
# ---------------------------------------------------------------------------
def merge_catalogs(existing: dict, new: dict) -> dict:
    merged = dict(existing)
    merged["library_paths"] = sorted(set(existing.get("library_paths", [])) | set(new.get("library_paths", [])))
    merged_blocks = dict(new.get("blocks", {}))
    for k, v in existing.get("blocks", {}).items():
        merged_blocks[k] = v
    merged["blocks"] = merged_blocks
    merged_sects = dict(new.get("mcc_sections", {}))
    for k, v in existing.get("mcc_sections", {}).items():
        merged_sects[k] = v
    merged["mcc_sections"] = merged_sects
    return merged


class _IntKeyDumper(yaml.Dumper):
    pass
_IntKeyDumper.add_representer(int, lambda d, v: d.represent_int(v))


def write_catalog(catalog: dict, out_path: Path):
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("# =============================================================================\n")
        fh.write("# MCC Block Catalog  (auto-generated by scripts/generate_catalog.py)\n")
        fh.write("# Review attribute_map in mcc_sections — confirm tags match your blocks.\n")
        fh.write("# Delete _detected_attributes keys once you have verified the attribute_map.\n")
        fh.write("# =============================================================================\n\n")
        yaml.dump(catalog, fh, Dumper=_IntKeyDumper, default_flow_style=False,
                  allow_unicode=True, sort_keys=False, width=120)
    print(f"Catalog written to: {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Generate mcc_block_catalog.yaml")
    parser.add_argument("--from-csv", default=None,
                        help="CSV produced by lisp/scan_blocks.lsp (recommended)")
    parser.add_argument("--dir",      required=True,
                        help="Directory containing .dwg block files")
    parser.add_argument("--out",      default=None, help="Output YAML path")
    parser.add_argument("--merge",    action="store_true")
    parser.add_argument("--verbose",  action="store_true")
    args = parser.parse_args()

    block_dir = Path(args.dir)
    if not block_dir.exists():
        print(f"ERROR: Directory not found: {block_dir}"); sys.exit(1)

    out_path = Path(args.out) if args.out else Path(__file__).parent.parent / "mcc_block_catalog.yaml"

    scan_data: dict[str, list[str]] = {}
    if args.from_csv:
        csv_path = Path(args.from_csv)
        if not csv_path.exists():
            print(f"ERROR: CSV not found: {csv_path}"); sys.exit(1)
        scan_data = load_csv(csv_path)
        print(f"Loaded attribute data for {len(scan_data)} files from {csv_path}\n")
    else:
        print("No --from-csv provided. All blocks will have empty attribute lists.")
        print("Run lisp/scan_blocks.lsp in AutoCAD first for best results.\n")

    catalog = build_catalog(block_dir, scan_data, args.verbose)

    if args.merge and out_path.exists():
        with open(out_path, "r", encoding="utf-8") as fh:
            existing = yaml.safe_load(fh)
        catalog = merge_catalogs(existing, catalog)

    write_catalog(catalog, out_path)

    n_sections = len(catalog.get("mcc_sections", {}))
    widths = sorted(k for k in catalog["mcc_sections"] if isinstance(k, int))
    print(f"{n_sections} section blocks detected" + (f" — widths: {widths}" if widths else ""))
    print(f"\nNext: open mcc_block_catalog.yaml and verify the attribute_map for each mcc_sections entry.")


if __name__ == "__main__":
    main()
